### ISSUE TITLE
capistrano 3.12.0

### ISSUE THREAD

**Issue by Eusebius1920** [groovenauts/capistrano-systemd-multiservice#14]
Can the gemspec relaxed to allow installation with recently released **capistrano 3.12.0**? Or are there any incompatibilities known?

If not: What has to be adjusted?

**Comment by Eusebius1920** [comment]
Changelog of capistrano 3.12.0:

https://github.com/capistrano/capistrano/releases/tag/v3.12.0

**Comment by minimum2scp** [comment]
@Eusebius1920 
Thanks for your information, I'll update in a few days.

**Comment by minimum2scp** [comment]
@Eusebius1920 
Released v0.1.0.beta8, please try.
