### ISSUE TITLE
Setup all registered services

### ISSUE THREAD

**Issue by camilohollanda** [groovenauts/capistrano-systemd-multiservice#27]
Is there an easy way to set up all registered services with a single command?

**Comment by minimum2scp** [comment]
No, but you can define your custom task like this:

```ruby
task :setup_all_services do
  invoke 'systemd:example1:setup'
  invoke 'systemd:example2:setup'
end
```

**Comment by camilohollanda** [comment]
I am intending to automate in a way that all services that were registered could be set up at once, without having to list each one of the services. But unfortunately, I am no expert in capistrano, so I don't know how to do that.

**Comment by minimum2scp** [comment]
> without having to list each one of the services

Hmm, I prefer to write all service names explicitly,
but you meen you don't want to write service names explicitly, like this?

```ruby
task :setup_all_services do
  some_method_returns_all_registered_services.each do |service_name|
    invoke "systemd:#{service_name}:setup"
  end
end
```

If you really want to do that, [ObjectSpace.each_object](https://docs.ruby-lang.org/en/3.0.0/ObjectSpace.html#method-c-each_object) returns registered services.

```ruby
task :setup_all_services do
  ObjectSpace.each_object(Capistrano::Systemd::MultiService::SystemService).map(&:app).each do |service_name|
    invoke "systemd:#{service_name}:setup"
  end
end
```

**Comment by camilohollanda** [comment]
Yeah that's exactly what I needed. Thank you very much.
