### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by ruanltbg** [groovenauts/capistrano-systemd-multiservice#34]
Hello I just spend some hours trying to discover why cap production `sytemd:{app}:setup` was not doing anything, I need to define a role in Capistrano otherwise it will not run. 

Can you update the docs to include this information? 

My setup was:
`server 'IP', primary: true`
now it is
`server 'IP', roles: %i[app], primary: true`

Thank you

**Comment by HLFH** [comment]
@ruanltbg This is detailed in the README.md file of the fork [capistrano-systemd-ng](https://github.com/HLFH/capistrano-systemd-ng).

**Comment by ruanltbg** [comment]
I guess that was on a prev doc, I guess I can close this one
