### ISSUE TITLE
Systemd doesn't re-read from symlinks

### ISSUE THREAD

**Issue by dukedorje** [groovenauts/capistrano-systemd-multiservice#5]
It doesn't re-read the symlink.  Whatever it pointed to when the daemon first started is what it will always be, rendering the "current" directory of capistrano non-functional.

**Comment by minimum2scp** [comment]
Thanks for your report.

Is this issue the same as https://unix.stackexchange.com/questions/241752/symlink-as-workingdirectory-in-systemd-service ?

**Comment by minimum2scp** [comment]
@dukejones 
Can you show me your service unit file?
Or, 
* Is `Environment = PWD=<%= current_path %>` line included in `[Service]` section?
* What is your application server? unicorn?

**Comment by dukedorje** [comment]
I believe my issue was due to an improper column type in my Postgres DB rather than not picking up changes when deploying.
I use Puma, BTW.  Closing this~ thanks!
