### ISSUE TITLE
Documentation Problem - Not apparent that the services aren't installed automatically

### ISSUE THREAD

**Issue by fuzzygroup** [groovenauts/capistrano-systemd-multiservice#6]
Hi, 

I'd recommend a change to the readme that indicates that you need to call capistrano with a setup command to get the services installed.  For example, given that I needed a unicorn service, I had to call:

bundle exec cap staging systemd:unicorn:setup --trace

(ignore the damn emoticon; that's supposed to be the word unicorn; all delimited by colons like invoking a rake task)

To get the unicorn service written to the remote box.  

It also wasn't apparent that services were named for the rails_app and then the tool (unicorn in this case).  Our app is named cas-seas3 so our service was named:

cas-seas3_unicorn.service

Overall thank you very much for the gem.  Just leaving our experiences here to help with docs or someone else in the future.

**Comment by minimum2scp** [comment]
@fuzzygroup 
Thanks for your report.

I will add the commands to setup systemd service
in example section (Rails application with unicorn and delayed_job),
and describe systemd service name.
